[[plugins]]
repo = 'AndrewRadev/switch.vim'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/vimshell.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'christoomey/vim-tmux-navigator'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'gregsexton/gitv'

[[plugins]]
repo = 'haya14busa/incsearch.vim'

[[plugins]]
repo = 'idanarye/vim-merginal'

# https://github.com/Shougo/dein.vim/issues/74#issuecomment-237198717
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

[[plugins]]
repo = 'junegunn/goyo.vim'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'kana/vim-textobj-line'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'mhinz/vim-signify'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'reedes/vim-pencil'

[[plugins]]
repo = 'reedes/vim-textobj-quote'

[[plugins]]
repo = 'reedes/vim-wordy'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'shuhei/asu2dark.vim'

[[plugins]]
repo = 'shuhei/vim-jours'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-sensible'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-unimpaired'

[[plugins]]
repo = 'tyru/open-browser.vim'

# -- Colorschemes

[[plugins]]
repo = 'dracula/vim'
as = 'dracula'

[[plugins]]
repo = 'ayu-theme/ayu-vim'

[[plugins]]
repo = 'arcticicestudio/nord-vim'

[[plugins]]
repo = 'sts10/vim-pink-moon'

[[plugins]]
repo = 'rakr/vim-two-firewatch'

[[plugins]]
repo = 'junegunn/seoul256.vim'

[[plugins]]
repo = 'haishanh/night-owl.vim'

[[plugins]]
repo = 'co1ncidence/mountaineer.vim'

[[plugins]]
repo = 'NLKNguyen/papercolor-theme'

# -- Language plugins, which don't have `plugin` directory and
#    not worth lazy plugins.
#    Use `:echo dein#check_lazy_plugins()` to find them.

[[plugins]]
repo = 'neoclide/jsonc.vim'

[[plugins]]
repo = 'tpope/vim-haml'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'hspec/hspec.vim'

[[plugins]]
repo = 'gorodinskiy/vim-coloresque'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'raichoo/purescript-vim'

[[plugins]]
repo = 'udalov/kotlin-vim'

[[plugins]]
repo = 'groenewege/vim-less'

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'

# yajs.vim doesn't work well with flowtype.
# This plugin is more accurate than vim-javascript.
# Consider using yajs.vim when I migrate all flowtype projects
# to TypeScript.
[[plugins]]
repo = 'yuezk/vim-js'

[[plugins]]
repo = 'jparise/vim-graphql'

[[plugins]]
repo = 'digitaltoad/vim-jade'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'gutenye/json5.vim'

[[plugins]]
repo = 'Glench/Vim-Jinja2-Syntax'

[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'

[[plugins]]
repo = 'liuchengxu/graphviz.vim'
