[[plugins]]
repo = 'AndrewRadev/switch.vim'

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/vimshell.vim'

[[plugins]]
repo = 'amix/vim-zenroom2'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
# If this doesn't work, manually fetch the next branch
# and run the build script.
rev = 'next'
build = 'bash install.sh'

[[plugins]]
repo = 'bling/vim-airline'

[[plugins]]
repo = 'christoomey/vim-tmux-navigator'

[[plugins]]
repo = 'dharanasoft/rtf-highlight'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'gorodinskiy/vim-coloresque'

[[plugins]]
repo = 'gregsexton/gitv'

[[plugins]]
repo = 'haya14busa/incsearch.vim'

[[plugins]]
repo = 'idanarye/vim-merginal'

[[plugins]]
repo = 'jordwalke/flatlandia'
depends = 'vim-airline'

[[plugins]]
repo = 'junegunn/fzf'
build = 'bash install.sh'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'junegunn/goyo.vim'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'kana/vim-textobj-line'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'mhinz/vim-signify'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'reedes/vim-pencil'

# For deoplete.nvim
[[plugins]]
repo = 'roxma/nvim-yarp'
if = '!has("nvim")'

# For deoplete.nvim
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = '!has("nvim")'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'shuhei/asu2dark.vim'

[[plugins]]
repo = 'shuhei/vim-jours'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-projectionist'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-sensible'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-unimpaired'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'wsdjeg/FlyGrep.vim'
